routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$this->get('pinfo', function() {
	echo phpinfo();
});

// Auth::routes();
// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
// $this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// $this->post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('news/{id}', 'MailPreviewController@html')->name('news.html');

Route::group(['middleware' => 'auth'], function() {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('contacts', 'ContactsController', ['only' => ['index', 'edit', 'create']]);
    Route::resource('communications', 'CommunicationsController', ['except' => ['store', 'update', 'destroy']]);
    Route::get('communications/create/{type}', 'CommunicationsController@create')->name('communications.create_type');
	Route::resource('users', 'UsersController', ['only' => ['index', 'edit', 'create']])->middleware('permission:edit_users');
});

Route::group(['prefix' => 'export'], function() {
    Route::get('contacts/{format}', 'ExportController@exportContacts');
});

Route::group(['prefix' => 'debug', 'middleware' => 'auth'], function() {
    Route::Get('mailable', function(\Illuminate\Http\Request $request) {
        $email = $request->get('email', env('ADMIN_EMAIL'));
        $url = $request->get('url', 'http://localhost');
        return new \ComHub\Mail\EmailConfirmation($email, $url);
    });
});

resources/views/communications/parts/header/pending.blade.php
<div uk-grid>
  <div class="uk-width-1-1 uk-text-center">
    <div>invio in corso</div>
    <a href="{{ route('communications.index') }}">Torna all'elenco</a>
  </div>
</div>

resources/views/communications/parts/header/ready.blade.php
<div uk-grid>
    <div class="uk-width-1-1 uk-width-1-2@s">
        <dl class="uk-description-list uk-description-list-divider">
            <dt>Potenziali Destinatari</dt>
            <dd>{{ $recipients_count }}</dd>
            @if ($communication->sent_error)
                <dt class="uk-text-danger">Errori</dt>
                <dd class="uk-text-danger">{{$communication->sent_error}}</dd>
            @endif
        </dl>
    </div>
    <div class="uk-width-1-1 uk-width-1-2@s">
        <a href="{{ route('communications.edit', $communication->id) }}"
           class="uk-button uk-button-default uk-button-large uk-width-1-1 uk-margin-bottom">
            <i uk-icon="icon: pencil"></i>
            Modifica
        </a>
        <ch-api-button
                class="uk-button-large uk-width-1-1"
                url="{{ route('api.communications.send', $communication->id) }}"
                method="put"
                button-text="{{ (empty($communication->sent_error)) ? 'Invia' : 'Reinvia' }}"
                button-type="primary"
                icon="play-circle"
                confirm-text="Inviare la comunicazione?"
                error-heading="<h3>Errore durante l'invio:</h3>"
                :enabled="{{ $recipients_count }} > 0"
                :redirect-on-success="true"
        ></ch-api-button>
    </div>
</div>

resources/views/communications/parts/header/sent.blade.php
<div uk-grid>
  <div class="uk-width-1-1 uk-width-1-2@s">
    <dl class="uk-description-list uk-description-list-divider">
      <dt>Inviata il</dt>
      <dd>{{ $communication->sent_done_at->formatLocalized('%d/%m/%Y') }}</dd>
      <dt>Destinatari</dt>
      <dd>{{ $communication->recipients_count }}</dd>
    </dl>
  </div>
  <div class="uk-width-1-1 uk-width-1-2@s">
    <ch-api-button
      class="uk-button-large uk-width-1-1"
      url="{{ route('api.communications.copy', $communication->id) }}"
      button-text="Duplica"
      icon="copy"
      confirm-text="Duplicare il contenuto selezionato?"
      error-heading="<h3>Errore durante la copia:</h3>"
    ></ch-api-button>
  </div>
</div>