routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$this->get('pinfo', function() {
	echo phpinfo();
});

// Auth::routes();
// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
// $this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// $this->post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('news/{id}', 'MailPreviewController@html')->name('news.html');

Route::group(['middleware' => 'auth'], function() {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('contacts', 'ContactsController', ['only' => ['index', 'edit', 'create']]);
    Route::resource('communications', 'CommunicationsController', ['except' => ['store', 'update', 'destroy']]);
    Route::get('communications/create/{type}', 'CommunicationsController@create')->name('communications.create_type');
	Route::resource('users', 'UsersController', ['only' => ['index', 'edit', 'create']])->middleware('permission:edit_users');
});

Route::group(['prefix' => 'export'], function() {
    Route::get('contacts/{format}', 'ExportController@exportContacts');
});

Route::group(['prefix' => 'debug', 'middleware' => 'auth'], function() {
    Route::Get('mailable', function(\Illuminate\Http\Request $request) {
        $email = $request->get('email', env('ADMIN_EMAIL'));
        $url = $request->get('url', 'http://localhost');
        return new \ComHub\Mail\EmailConfirmation($email, $url);
    });
});

app/User.php
<?php

namespace ComHub;

use ComHub\Traits\Filtrable;
use ComHub\Traits\HasRolesAndPermissions;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
	use HasApiTokens, SoftDeletes, Notifiable, Filtrable, HasRolesAndPermissions;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

	public function contacts()
	{
		return $this->hasMany(Contact::class);
	}

}

app/Http/Controllers/UsersController.php
<?php

namespace ComHub\Http\Controllers;

use Illuminate\Http\Request;

class UsersController extends Controller
{
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index()
	{
		return view('users.index');
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		return view('users.create');
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id)
	{
		return view('users.edit')->with(['id' => $id]);
	}
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
    <ch-form
            url="{{ route('api.users.store') }}"
            close-uri="{{ route('users.index') }}"
            :is-new="true"
            :deletable="false"
            :success-modal-buttons="{
      'ok_label': 'CONTINUA',
      'cancel_label': 'CHIUDI',
      'ok_url': '{{ route('users.create') }}',
      'cancel_url': '{{ route('users.index') }}'
    }"
    >
        @include('users.parts.form')
    </ch-form>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <ch-form
            url="{{ route('api.users.show', $id) }}"
            close-uri="{{ route('users.index') }}"
            :success-modal-buttons="{
      'ok_label': 'CONTINUA',
      'cancel_label': 'CHIUDI',
      'cancel_url': '{{ route('users.index') }}'
    }"
    >
        @include('users.parts.form')
    </ch-form>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
    <a href="{{ route('users.create') }}" class="uk-button uk-button-primary uk-margin-bottom">Nuovo Utente</a>
    <ch-table
            url="{{ route('api.users.index') }}"
            :fields="[
        {
          name: 'name',
          sortable: true,
          label: 'Nome'
        },
        {
          name: 'email',
          sortable: true,
          label: 'Email'
        }
      ]"
    >
    </ch-table>
@endsection