routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$this->get('pinfo', function() {
	echo phpinfo();
});

// Auth::routes();
// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
// $this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// $this->post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('news/{id}', 'MailPreviewController@html')->name('news.html');

Route::group(['middleware' => 'auth'], function() {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('contacts', 'ContactsController', ['only' => ['index', 'edit', 'create']]);
    Route::resource('communications', 'CommunicationsController', ['except' => ['store', 'update', 'destroy']]);
    Route::get('communications/create/{type}', 'CommunicationsController@create')->name('communications.create_type');
	Route::resource('users', 'UsersController', ['only' => ['index', 'edit', 'create']])->middleware('permission:edit_users');
});

Route::group(['prefix' => 'export'], function() {
    Route::get('contacts/{format}', 'ExportController@exportContacts');
});

Route::group(['prefix' => 'debug', 'middleware' => 'auth'], function() {
    Route::Get('mailable', function(\Illuminate\Http\Request $request) {
        $email = $request->get('email', env('ADMIN_EMAIL'));
        $url = $request->get('url', 'http://localhost');
        return new \ComHub\Mail\EmailConfirmation($email, $url);
    });
});

app/Contact.php
<?php

namespace ComHub;

use Carbon\Carbon;
use ComHub\Services\ComuneIstat;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Str;
use ComHub\Traits\Filtrable;
use Validator;

class Contact extends Model
{
    use SoftDeletes, Filtrable, Notifiable;

    protected $fillable = [
        'firstname',
        'lastname',
        'gender',
        'birthdate',
        'email',
        'email_confirmed_at',
        'email_subscribed_at',
        'email_unsubscribed_at',
        'phone',
        'phone_confirmed_at',
        'phone_subscribed_at',
        'phone_unsubscribed_at',
        'address_name',
	    'address_number',
        'zip_code',
	    'notes',
	    'source',
        'representative',
        'privacy_accepted_at',

	    // Relationships
	    'city_id',
	    'user_id',

        // Virtual
        'email_is_subscribed',
        'phone_is_subscribed',
        'email_is_confirmed',
        'phone_is_confirmed',
        'privacy'
    ];

    protected $dates = [
        'birthdate',
        'email_confirmed_at',
        'phone_confirmed_at',
        'email_subscribed_at',
        'email_unsubscribed_at',
        'phone_subscribed_at',
        'phone_unsubscribed_at',
        'deleted_at',
        'privacy_accepted_at',
    ];

    protected $appends = [
        'email_is_subscribed',
        'phone_is_subscribed',
        'privacy',
    ];

	public function scopeOwned($query, $userId = null)
	{
		if (\Auth::user()->hasPermission('view_all_contacts')) return $query;
		$userId = ($userId == null) ? \Auth::user()->id : $userId;
		return $query->where('user_id', $userId);
	}


	public function scopeEmailable($query) {
        return $query->whereNotNull('email')->whereNotNull('email_confirmed_at');
    }

    public function scopeTextable($query) {
        return $query->whereNotNull('phone')->whereNotNull('phone_confirmed_at');
    }

    public function scopeNotifiable($query, $field)
    {
        return $query->where( function($query) use ($field) {
            return $query->whereNotNull($field)
                         ->whereNotNull($field.'_confirmed_at')
                         ->whereNotNull($field.'_subscribed_at')
                         ->whereNull($field.'_unsubscribed_at');
        });
    }

    public function generateToken() {
        return Str::random(60);
    }

    public function getEmailIsSubscribedAttribute() {
	    if (empty($this->attributes['email_subscribed_at'])) return null;
	    return !empty($this->attributes['email_subscribed_at']) && empty($this->attributes['email_unsubscribed_at']);
    }

    public function setEmailIsSubscribedAttribute($val) {
	    if ($val === null) return;
	    if ($val) {
            if (empty($this->attributes['email_unsubscribed_at'])) {
                $this->attributes['email_subscribed_at'] = Carbon::now();
            } else {
                $this->attributes['email_unsubscribed_at'] = null;
            }
        } else {
            $this->attributes['email_unsubscribed_at'] = Carbon::now();
        }
    }

    public function getPhoneIsSubscribedAttribute() {
	    if (empty($this->attributes['phone_subscribed_at'])) return null;
	    return !empty($this->attributes['phone_subscribed_at']) && empty($this->attributes['phone_unsubscribed_at']);
    }

    public function setPhoneIsSubscribedAttribute($val) {
	    if ($val === null) return;
	    if ($val) {
            $this->attributes['phone_subscribed_at'] = Carbon::now();
            if (!empty($this->attributes['phone_unsubscribed_at'])) {
                $this->attributes['phone_unsubscribed_at'] = null;
            }
        } else {
            $this->attributes['phone_unsubscribed_at'] = Carbon::now();
        }
    }

    public function setEmailIsConfirmedAttribute($val) {
        if ($val && empty($this->attributes['email_confirmed_at']) && !empty($this->attributes['email'])) {
            $this->attributes['email_confirmed_at'] = Carbon::now();
        }
    }

    public function setPhoneIsConfirmedAttribute($val) {
        if ($val && empty($this->attributes['phone_confirmed_at']) && !empty($this->attributes['phone'])) {
            $this->attributes['phone_confirmed_at'] = Carbon::now();
        }
    }

	public function getBirthdateAttribute() {
		if ($this->attributes['birthdate'])
			return (new Carbon($this->attributes['birthdate']))->format('d/m/Y');
		return null;
	}

	public function setBirthdateAttribute($val) {
		try {
			$birthdate = Carbon::createFromFormat('d/m/Y', $val);
		} catch(\InvalidArgumentException $e) {
			$birthdate = null;
		}
		$this->attributes['birthdate'] = $birthdate;
    }

    public function setPrivacyAttribute($val) {
        if (empty($this->attributes['privacy_accepted_at'])) {
            $this->attributes['privacy_accepted_at'] = Carbon::now();
        }
    }

    public function getPrivacyAttribute() {
        return !empty($this->attributes['privacy_accepted_at']);
    }

	public function routeNotificationForSkebby() {
      if (
        !Validator::make(
            [
                'phone' => $this->phone
            ],
            [
                'phone' => ['required', 'phone:IT']
            ]
        )->fails()
      ) {
          return $this->phone;
      }
      return null;
    }

	public function user()
	{
		return $this->belongsTo(User::class);
	}

	public function city()
	{
		return $this->belongsTo(ComuneIstat::class);
	}

	public function communications()
	{
		return $this->belongsToMany(Communication::class)->withTimestamps();
	}

}

app/Http/Controllers/ContactsController.php
<?php

namespace ComHub\Http\Controllers;

use Illuminate\Http\Request;

class ContactsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('contacts.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('contacts.create');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('contacts.edit')->with('id', $id);
    }
}

resources/views/contacts/create.blade.php
@extends('layouts.app')

@section('content')
  <ch-form
    url="{{ route('api.contacts.store') }}"
    close-uri="{{ route('contacts.index') }}"
    :is-new="true"
    :deletable="false"
    :success-modal-buttons="{
      'ok_label': 'CONTINUA',
      'cancel_label': 'CHIUDI',
      'ok_url': '{{ route('contacts.create') }}',
      'cancel_url': '{{ route('contacts.index') }}'
    }"
  >
    @include('contacts.parts.form')
  </ch-form>
@endsection

resources/views/contacts/edit.blade.php
@extends('layouts.app')

@section('content')
  <ch-form
    url="{{ route('api.contacts.show', $id) }}"
    close-uri="{{ route('contacts.index') }}"
    :success-modal-buttons="{
      'ok_label': 'CONTINUA',
      'cancel_label': 'CHIUDI',
      'cancel_url': '{{ route('contacts.index') }}'
    }"
  >
    @include('contacts.parts.form')
  </ch-form>
@endsection

resources/views/contacts/index.blade.php
@extends('layouts.app')

@section('content')
    <a href="{{ route('contacts.create') }}" class="uk-button uk-button-primary uk-margin-bottom">Nuovo Contatto</a>
    <ch-table
            url="{{ route('api.contacts.index') }}"
            :export-formats="[
        {
          id: 'csv',
          label: 'CSV',
          url: '{{ url('export/contacts/csv') }}'
        },
        {
          id: 'excel',
          label: 'Excel',
          url: '{{ url('export/contacts/xls') }}'
        }
      ]"
            :fields="[
        {
          name: 'firstname',
          sortable: true,
          label: 'Nome'
        },
        {
          name: 'lastname',
          sortable: true,
          label: 'Cognome'
        },
        {
          name: 'birthdate',
          sortable: true,
          label: 'Data di nascita'
        },
        {
          name: 'slot:email',
          sortable: true,
          label: 'Email',
          orderField: 'email'
        },
        {
          name: 'phone',
          label: 'Telefono'
        },
        {
          name: 'slot:subscriptions',
          label: 'Iscrizioni'
        },
        {
          name: 'slot:city',
          orderField: 'city.denominazione_corrente',
          label: 'Città'
        },
        {
          name: 'source',
          sortable: true,
          label: 'Provenienza'
        }
      ]"
    >
        <div slot="filters" slot-scope="props" class="uk-tile uk-tile-muted uk-padding-remove">
            <button class="uk-button uk-button-primary uk-width-1-1" uk-toggle="target: #table-filters">Filtri <i
                        uk-icon="icon: settings"></i></button>
            <div id="table-filters" class="uk-tile uk-padding-small">
                <div uk-grid>
                    <div class="uk-width-1-1 uk-width-1-2@s uk-width-1-6@m">
                        <label class="uk-form-label" for="ch-filter-gender">Sesso</label>
                        <div class="uk-form-controls">
                            <select class="uk-select" id="ch-filter-gender" v-model="props.filters.gender">
                                <option value=""></option>
                                <option value="M">M</option>
                                <option value="F">F</option>
                            </select>
                        </div>
                    </div>
                    <div class="uk-width-1-1 uk-width-1-2@s uk-width-1-6@m">
                        <label class="uk-form-label">Età</label>
                        <div class="uk-grid-small" uk-grid>
                            <div class="uk-width-1-2">
                                <div class="uk-form-controls">
                                    <input type="text" id="ch-filter-age-min" class="uk-input"
                                           v-model.lazy="props.filters.age_min" placeholder="Da"/>
                                </div>
                            </div>
                            <div class="uk-width-1-2">
                                <div class="uk-form-controls">
                                    <input type="text" id="ch-filter-age-max" class="uk-input"
                                           v-model.lazy="props.filters.age_max" placeholder="A"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="uk-width-1-1 uk-width-1-2@s uk-width-1-6@m">
                        <label class="uk-form-label" for="ch-filter-email_state">Email</label>
                        <div class="uk-form-controls">
                            <select class="uk-select" id="ch-filter-email_state" v-model="props.filters.email_state">
                                <option value=""></option>
                                <option value="available">Inserita</option>
                                <option value="empty">Non inserita</option>
                                <option value="confirmed">Confermata</option>
                                <option value="subscribed">Iscritta</option>
                                <option value="unsubscribed">Non iscritta</option>
                            </select>
                        </div>
                    </div>
                    <div class="uk-width-1-1 uk-width-1-2@s uk-width-1-6@m">
                        <label class="uk-form-label" for="ch-filter-phone_state">Telefono</label>
                        <div class="uk-form-controls">
                            <select class="uk-select" id="ch-filter-phone_state" v-model="props.filters.phone_state">
                                <option value=""></option>
                                <option value="available">Inserito</option>
                                <option value="empty">Non inserito</option>
                                <option value="confirmed">Confermato</option>
                                <option value="subscribed">Iscritto</option>
                                <option value="unsubscribed">Non iscritto</option>
                            </select>
                        </div>
                    </div>
                    <div class="uk-width-1-1 uk-width-1-3@m">
                        <label class="uk-form-label" for="ch-filter-source">Provenienza</label>
                        <ch-select
                            class="uk-form-controls"
                            v-model="props.filters.source"
                            :init="true"
                            url="/api/data/contacts/source"
                        >
                        </ch-select>
                    </div>
                    <div class="uk-width-1-1 uk-width-1-3@m">
                        <label class="uk-form-label" for="ch-filter-city">Comune</label>
                        <ch-select
                            class="uk-form-controls"
                            label="denominazione_corrente"
                            v-model="props.filters.city"
                            url="/api/data/comuni"
                        >
                        </ch-select>
                    </div>
                </div>
            </div>
        </div>
        <div slot="subscriptions" slot-scope="props">
            <p v-if="props.item.email_is_subscribed && props.item.phone_is_subscribed">Email, SMS</p>
            <p v-else-if="props.item.email_is_subscribed">Email</p>
            <p v-else-if="props.item.phone_is_subscribed">SMS</p>
            <p v-else>-</p>
        </div>
        <div slot="email" slot-scope="props" v-text="(props.item.email) ? props.item.email : '-'" :class="{ 'uk-text-primary': props.item.email_confirmed_at }"></div>
        <div slot="city" slot-scope="props" v-text="(props.item.city) ? props.item.city.denominazione_corrente : '-'"></div>
    </ch-table>
@endsection