routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$this->get('pinfo', function() {
	echo phpinfo();
});

// Auth::routes();
// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
// $this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// $this->post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('news/{id}', 'MailPreviewController@html')->name('news.html');

Route::group(['middleware' => 'auth'], function() {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('contacts', 'ContactsController', ['only' => ['index', 'edit', 'create']]);
    Route::resource('communications', 'CommunicationsController', ['except' => ['store', 'update', 'destroy']]);
    Route::get('communications/create/{type}', 'CommunicationsController@create')->name('communications.create_type');
	Route::resource('users', 'UsersController', ['only' => ['index', 'edit', 'create']])->middleware('permission:edit_users');
});

Route::group(['prefix' => 'export'], function() {
    Route::get('contacts/{format}', 'ExportController@exportContacts');
});

Route::group(['prefix' => 'debug', 'middleware' => 'auth'], function() {
    Route::Get('mailable', function(\Illuminate\Http\Request $request) {
        $email = $request->get('email', env('ADMIN_EMAIL'));
        $url = $request->get('url', 'http://localhost');
        return new \ComHub\Mail\EmailConfirmation($email, $url);
    });
});

app/Communication.php
<?php

namespace ComHub;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use ComHub\Traits\Filtrable;

class Communication extends Model
{

    const READY = 'ready';
    const PENDING = 'pending';
    const SENT = 'sent';

    use SoftDeletes, Filtrable;

    protected $fillable = [
    	'title',
        'subject',
        'header',
        'body',
	    'type_id',
	    'segment_id',
	    'filters',
    ];

    protected $dates = [
        'deleted_at',
        'sent_request_at',
        'sent_done_at',
    ];

    protected $casts = [
    	'filters' => 'json',
	    'sent_error' => 'json'
    ];

    protected $appends = [ 'sent', 'state' ];

    public function getSentAttribute()
    {
        return !empty($this->attributes['sent_done_at']);
    }

    public function getStateAttribute()
    {
        if (!empty($this->attributes['sent_request_at'])) {
            $state = (empty($this->attributes['sent_done_at'])) ? self::PENDING : self::SENT;
        } else {
            $state = self::READY;
        }
        return $state;
    }

    public function getBatches()
    {
        return ceil($this->contacts()->count() / $this->type->quantity);
    }

    public function getCost()
    {
        return $this->type->price * $this->getBatches();
    }

    public function getCreditLabel()
    {
        return $this->attributes['subject'] ?? 'Comunication '.$this->getKey();
    }

    // TODO: create trait ExternalReferenceable with defeault methods and necessary properties
    public function getReference()
    {
    	return str_slug(config('app.name')) . '_' . $this->getKey();
    }

    public function countRecipients()
    {
	    return Contact::notifiable($this->type->route)->get()->filter(
		    function ($contact) {
			    return !!$contact->routeNotificationForSkebby();
		    }
	    )->count();
    }

    public function type()
    {
    	return $this->belongsTo(CommunicationType::class);
    }

    public function segment()
    {
    	return $this->belongsTo(Segment::class);
    }

    public function user()
    {
    	return $this->belongsTo(User::class);
    }

    public function contacts()
    {
    	return $this->belongsToMany(Contact::class)->withTimestamps();
    }

    public function credits()
    {
    	return $this->morphToMany(Credit::class, 'accreditable')->withTimestamps();
    }
}

app/CommunicationType.php
<?php

namespace ComHub;

use ComHub\Traits\Filtrable;
use Illuminate\Database\Eloquent\Model;

class CommunicationType extends Model
{
	use Filtrable;

    protected $fillable = [
    	'name',
	    'route',
	    'price',
	    'quantity'
    ];

	public function getPriceAttribute()
	{
		return $this->attributes['price'] / 100;
	}

	public function setPriceAttribute($val)
	{
		$this->attributes['price'] = $val * 100;
	}

	public function communications()
	{
		return $this->hasMany(Communication::class);
	}
}

app/Http/Controllers/CommunicationsController.php
<?php

namespace ComHub\Http\Controllers;

use ComHub\CommunicationType;
use Illuminate\Http\Request;
use ComHub\Communication;
use ComHub\Contact;

class CommunicationsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('communications.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($type = null)
    {
    	$type_id = null;
    	if ($type) {
    		$comm = CommunicationType::where('name', $type)->first();
    		if ($comm) $type_id = $comm->id;
	    }
        return view('communications.create')->with([
        	'type_id' => $type_id
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $communication = Communication::findOrFail($id);
        $recipients_count = $communication->contacts()->count();
        return view('communications.show')->with([
            'communication' =>$communication,
            'recipients_count' => $recipients_count
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('communications.edit')->with(['id' => $id]);
    }
}

resources/views/communications/create.blade.php
@extends('layouts.app')

@section('content')
<ch-form
  url="{{ route('api.communications.store') }}"
  :is-new="true"
  :deletable="false"
  :default-data="{type_id: {{ ($type_id) ?? 'null' }},type: {}, segment_id: null}"
  :edit-on-create="false"
>
  @include('communications.parts.form')
</ch-form>
@endsection

resources/views/communications/edit.blade.php
@extends('layouts.app')

@section('content')
  <ch-form
    url="{{ route('api.communications.show', $id) }}"
    close-uri="{{ route('communications.index') }}"
    :show-on-update="true"
  >
    @include('communications.parts.form')
  </ch-form>
@endsection

resources/views/communications/index.blade.php
@extends('layouts.app')

@section('content')
  <a href="{{ route('communications.create') }}" class="uk-button uk-button-primary uk-margin-bottom">Nuova Comunicazione</a>
    <ch-table
      url="{{ route('api.communications.index') }}"
      :fields="[
        {
          name: 'title',
          sortable: true,
          label: 'Titolo'
        },
        {
          name: 'slot:type',
          label: 'Tipo'
        },
        {
          name: 'slot:created_at',
          sortable: true,
          label: 'Creato il',
          orderField: 'created_at',
        },
        {
          name: 'sent_at',
          sortable: true,
          label: 'Inviato il'
        },
        {
          name: 'slot:actions'
        }
      ]"
      :edit-on-click="false"
    >
      <div slot="actions" slot-scope="props" class="uk-child-width-1-2 uk-grid-collapse" uk-grid>
        <a v-if="props.item.state === 'ready'" class="uk-icon-link uk-text-center" uk-icon="icon: pencil; ratio: 1.5" :href="'communications/'+props.item.id+'/edit'"></a>
        <ch-api-button
          v-if="props.item.state !== 'sent'"
          :url="'api/communications/'+props.item.id+'/send'"
          method="put"
          button-type="link"
          icon="play-circle"
          icon-ratio="1.5"
          confirm-text="Inviare la comunicazione?"
          error-heading="<h3>Errore durante l'invio:</h3>"
          :enabled="props.item.state === 'ready'"
        ></ch-api-button>
        <ch-api-button
          v-else
          class="uk-text-muted"
          :url="'api/communications/'+props.item.id+'/copy'"
          button-type="link"
          icon="copy"
          icon-ratio="1.5"
          confirm-text="Duplicare il contenuto selezionato?"
          error-heading="<h3>Errore durante la copia:</h3>"
        ></ch-api-button>
      </div>
      <div slot="created_at" slot-scope="props" v-text="new Date(props.item.created_at).toLocaleDateString()"></div>
      <div slot="type" slot-scope="props" v-text="(props.item.type) ? props.item.type.name : '-'"></div>
    </ch-table>
@endsection

resources/views/communications/show.blade.php
@extends('layouts.app')

@section('content')
<div class="uk-width-1-1">
    <div :uk-sticky="'offset: 80; bottom: #communication-form'">
        <div class="uk-tile uk-tile-muted uk-padding-small">
            <div class="uk-child-width-1-2 uk-grid-collapse" uk-grid>
                <div>Costo: {{ $communication->getCost() }}</div>
                <ch-api-label
                        class="uk-text-right"
                        url="{{ route('api.credits.balance') }}"
                        format="Credito attuale: %field%"
                ></ch-api-label>
            </div>
        </div>
    </div>
</div>
<h2 class="uk-heading-divider">{{ $communication->title }}</h2>
@include("communications.parts.header.{$communication->state}")
@if($communication->type->template)
    @include("communications.parts.preview.template")
@else
    @include("communications.parts.preview.plain")
@endif
@endsection